tempo:
    retention: 168h
    receivers:
        otlp:
            protocols:
                grpc: { endpoint: 0.0.0.0:4317 }
                http: { endpoint: 0.0.0.0:4318 }

persistence:
    enabled: true
    size: 30Gi

serviceMonitor:
    enabled: true
    labels: { release: kube-prometheus-stack }
